name: Guiced Inject
on:
  workflow_dispatch:
    inputs:
      centralRelease:
        type: boolean
        description: Run a release to maven central
        default: false
  push:
jobs:
  GuicedInjection:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: ''
      name: 'Guiced Injection'
      sonarProjectName: 'GuicedEE_GuicedInjection'
      sonarOrganization: 'guicedee'
    secrets: inherit