name: Guiced Inject
on:
  workflow_dispatch:
    inputs:
      centralRelease:
        type: boolean
        description: Run a release to maven central
        default: false
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - master


permissions:
  contents: write
  packages: write
  checks: write
  pull-requests: write

jobs:
  verify:
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: ''
      name: 'Guiced Injection'
      sonarProjectName: 'GuicedEE_GuicedInjection'
      sonarOrganization: 'guicedee'
      skipDeploy: 'true'
    secrets: inherit
  deploy:
    if: >-
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: ''
      name: 'Guiced Injection'
      sonarProjectName: 'GuicedEE_GuicedInjection'
      sonarOrganization: 'guicedee'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
